# Generated by Django 3.1.3 on 2020-11-05 12:18

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Kenya', max_length=120)),
                ('population', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_name', to=settings.AUTH_USER_MODEL)),
                ('neighbourhod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='hood.hood')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=120)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.neighbourhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('neighbour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbour_name', to='hood.hood')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_profile', to='hood.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(max_length=1000, verbose_name='job_description')),
                ('business_email', models.EmailField(max_length=254)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.neighbourhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to='hood.profile')),
            ],
        ),
    ]
