# Generated by Django 3.1.3 on 2020-11-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='neighbourhod',
            new_name='neighbourhood',
        ),
    ]
